#ifndef __ZYNQ_UART_H
#define __ZYNQ_UART_H

#include <stdint.h>

#define ZUART_BASEADDR (0x40002000)
#define ZUART_RX_FIFO_OFFSET (0x0000U)
#define ZUART_TX_FIFO_OFFSET (0x0004U)
#define ZUART_STATUS_OFFSET (0x0008U)
#define ZUART_CTRL_OFFSET (0x000CU)
#define ZUART_RX_FIFO (ZUART_BASEADDR + ZUART_RX_FIFO_OFFSET)
#define ZUART_TX_FIFO (ZUART_BASEADDR + ZUART_TX_FIFO_OFFSET)
#define ZUART_REG_STATUS (ZUART_BASEADDR + ZUART_STATUS_OFFSET)
#define ZUART_REG_CTRL (ZUART_BASEADDR + ZUART_CTRL_OFFSET)

void ZUART_SendByte(uint8_t data);
uint8_t ZUART_ReadByte(void);


#endif
