set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports SWCLK]
set_property IOSTANDARD LVCMOS33 [get_ports RST]
set_property IOSTANDARD LVCMOS33 [get_ports UART_RX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_TX]
set_property PACKAGE_PIN K17 [get_ports CLK]
set_property PACKAGE_PIN N18 [get_ports SWCLK]
set_property IOSTANDARD LVCMOS33 [get_ports SWDIO]
set_property PACKAGE_PIN M20 [get_ports RST]
set_property PACKAGE_PIN P19 [get_ports SWDIO]
set_property PACKAGE_PIN N20 [get_ports UART_RX]
set_property PACKAGE_PIN P20 [get_ports UART_TX]

create_clock -period 20.000 -name CLK -waveform {0.000 10.000} [get_ports CLK]
create_clock -period 100.000 -name SWCLK -waveform {0.000 50.000} [get_ports SWCLK]

set_property IOSTANDARD LVCMOS33 [get_ports {GPIOA_tri_io[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIOA_tri_io[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIOA_tri_io[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIOA_tri_io[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIOA_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIOA_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIOA_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIOA_tri_io[0]}]
set_property PACKAGE_PIN T12 [get_ports {GPIOA_tri_io[7]}]
set_property PACKAGE_PIN U12 [get_ports {GPIOA_tri_io[6]}]
set_property PACKAGE_PIN V12 [get_ports {GPIOA_tri_io[5]}]
set_property PACKAGE_PIN W13 [get_ports {GPIOA_tri_io[4]}]
set_property PACKAGE_PIN T20 [get_ports {GPIOA_tri_io[3]}]
set_property PACKAGE_PIN U20 [get_ports {GPIOA_tri_io[2]}]
set_property PACKAGE_PIN V20 [get_ports {GPIOA_tri_io[1]}]
set_property PACKAGE_PIN W20 [get_ports {GPIOA_tri_io[0]}]
